version: '3'

services:
  backend:
    image: node:16-alpine
    command:
      - sh
      - -c
      - |
        cd backend
        yarn
        yarn start:dev
    volumes:
      - './app:/usr/src/app'
      - 'back-node-deps:/usr/src/app/node_modules'
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    tty: true

  frontend:
    image: node:16-alpine
    command:
      - sh
      - -c
      - |
        yarn
        yarn storybook &
        yarn start
    volumes:
      - './app/frontend:/usr/src/app'
      - 'front-node-deps:/usr/src/app/node_modules'
    working_dir: /usr/src/app
    ports:
      - '3030:3030'
      - '6006:6006'
    tty: true

  mongo:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb

volumes:
  back-node-deps:
  front-node-deps:
  mongodata:
  mongoconfig:
