version: '3'

services:
  app:
    image: node:16
    command: bash -c "yarn && yarn start:dev"
    restart: unless-stopped
    volumes:
      - '.:/usr/src/app'
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    tty: true

  mongo:
    restart: unless-stopped
    image: mongo:5.0
    ports:
      - '127.0.0.1:27017:27017'
