version: '3'

services:
  app:
    image: codexteamuser/task-manager:prod
    build:
      context: .
      dockerfile: 'docker/Dockerfile'
    restart: unless-stopped
    volumes:
      - ./app/backend/.env:/usr/src/app/backend/.env
    ports:
      - '127.0.0.1:3000:3000'
      - '127.0.0.1:3080:3080'

  mongo:
    restart: unless-stopped
    image: mongo:5.0
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodata:
  mongoconfig:
