version: '3'

services:
  app:
    build:
      context: .
      dockerfile: 'docker/Dockerfile'
    restart: unless-stopped
    volumes:
      - '.env:/usr/app/.env'

  mongo:
    restart: unless-stopped
    image: mongo:5.0

  e2e:
    image: cypress
    build: ./e2e
    container_name: cypress
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app:3000
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
