name: Run cypress tests

on: [pull_request]

jobs:
  cypress:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build and run the stack
        run: docker-compose -f docker-compose.test.yml up -d

      - run: |
          cd e2e
          npm install
          npx cypress run


#      - name: Run tests
#        run: docker-compose -f docker-compose.test.yml exec -T -e COMPOSE_INTERACTIVE_NO_CLI=1 cypress npx cypress run
